apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.openai.apiKey | b64enc }}
---

apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
type: Opaque
data:
  DOCKER_USER: {{ .Values.docker.dockerUser | b64enc }}
  DOCKER_TOKEN: {{ .Values.docker.dockerToken | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "application-template.imagePullSecret" . }}

