apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
imagePullSecrets:
  - name: docker-registry-secret
